name: uds
channels:
  - conda-forge
  - defaults
dependencies:
  - defaults::python    
  - defaults::notebook
  - defaults::jupyterlab
  - defaults::pip
  - cenpy  
  - numpy    
  - pandas 
  - geopandas
  - contextily
  - requests
  - shapely
  - bs4
  - matplotlib
  - seaborn
  - PyPDF2
  - pdfminer.six
  - nltk
  - gensim
  - openpyxl
  - pyLDAvis
  - textblob
  - scikit-learn
  - pandasql
  - sqlalchemy 
  - praw
  - wordcloud
  - pip:
    - pygris  # conda support forthcoming
    - partridge
